name: AndroidBuild
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Upload and Distribute App
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
            serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
            appId: ${{ secrets.FIREBASE_APP_ID }}
            file: app/build/outputs/apk/debug/app-debug.apk
            groups: 'testers'
